import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms for using Nexora AI.",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: 720, margin: "0 auto", padding: "64px 24px", color: "#edeef4" }}>
      <h1 style={{ fontFamily: "Fraunces, serif", fontSize: 32, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: "#9a9ab0", marginBottom: 32 }}>Last updated: September 2026</p>

      <section style={{ marginBottom: 28, lineHeight: 1.7 }}>
        <h2 style={{ fontSize: 18, marginBottom: 8 }}>Using Nexora AI</h2>
        <p>
          Nexora AI is an AI chat assistant. Responses are generated by a third-party language
          model and can be incomplete, outdated, or wrong — verify anything important before
          relying on it.
        </p>
      </section>

      <section style={{ marginBottom: 28, lineHeight: 1.7 }}>
        <h2 style={{ fontSize: 18, marginBottom: 8 }}>Acceptable use</h2>
        <p>
          Don&apos;t use Nexora AI to generate content that is illegal, harmful, or infringes on
          others&apos; rights. We may suspend access for accounts that misuse the service.
        </p>
      </section>

      <section style={{ marginBottom: 28, lineHeight: 1.7 }}>
        <h2 style={{ fontSize: 18, marginBottom: 8 }}>No warranty</h2>
        <p>
          The service is provided &quot;as is,&quot; without warranties of any kind. We aren&apos;t liable
          for decisions made based on the assistant&apos;s output.
        </p>
      </section>

      <section style={{ marginBottom: 28, lineHeight: 1.7 }}>
        <h2 style={{ fontSize: 18, marginBottom: 8 }}>Changes</h2>
        <p>We may update these terms as the product changes. Continued use means you accept the current version.</p>
      </section>
    </main>
  );
}
